#!/bin/sh

#
#  (COPYRIGHT) Copyright (C) 2008, 2009, The ONS Team.
#  This file is part of ONS, see COPYING for details.
#

#
# File information:
# - Created: 19. April 2008
# - Lead-Dev: - David Herrmann
# - Contributors: /
# - Last-Change: 15. March 2009
#

#
# This script cleans the whole GIT repository. If you do not have a
# local copy of the GIT repo, this script does nothing.
#
# This script should only be used by developers. Users can safely
# ignore this script.
#


echo "                                                "
echo "           #####################                "
echo "           ##    ONS clean    ##                "
echo "           #####################                "
echo "                                                "
echo "This script cleans the GIT repository directory."
echo "     It should only be used by developers.      "
echo "                                                "


# We try to find the directory of this script and change
# into the "libraries" subdir.
if test -d ../libraries ; then
    cd ..
fi
if test -d ../../libraries ; then
    cd ../..
fi
if test -d ../../../libraries ; then
    cd ../../..
fi


# We check whether we are in the right directory. I guess there
# is a builtin way to do this but I don't know bash very well
# and this works, too.
if test -f ./clean ; then
    CREATION_TIME=$(grep Created ./clean | grep -v TIME)
    if test "$CREATION_TIME" != "# - Created: 19. April 2008" ; then
        echo "Error: Please change into the directory of the ./clean script."
        exit 1;
    fi
else
    echo "Error: Please change into the directory of the ./clean script."
    exit 1;
fi


# Remove every file which is not under revision control.
if test -d .git ; then
    rm .gitignore
    git clean -df
    git checkout .gitignore
    echo "Successfully cleaned the directory."
else
    echo "Error: You do not use a development repository."
fi

