#!/bin/sh

#
#  (COPYRIGHT) Copyright (C) 2008, 2009, The ONS Team.
#  This file is part of ONS, see COPYING for details.
#

#
# File information:
# - Created: 19. April 2008
# - Lead-Dev: - David Herrmann
# - Contributors: /
# - Last-Change: 1. January 2009
#

#
# You can clean all unnecessary stuff with "./clean".
# Please use it only if you got the source from the development repos.
#

# We try to find the directory of this script and change
# into the "libraries" subdir.
if test -d ../libraries ; then
    cd ..
fi
if test -d ../../libraries ; then
    cd ../..
fi
if test -d ../../../libraries ; then
    cd ../../..
fi


# We check whether we are in the right directory. I guess there
# is a builtin way to do this but I don't know bash this well
# and this works, too.
if test -f ./clean ; then
    CREATION_TIME=$(grep Created ./clean | grep -v TIME)
    if test "$CREATION_TIME" != "# - Created: 19. April 2008" ; then
        echo "Invalid directory."
        exit 1;
    fi
else
    echo "Invalid directory."
    exit 1;
fi

# Remove every file which is not under revision control.
# "hg status -nu0" does not list empty directory. We remove
# them manually.
if test -d .git ; then
    git clean -df
    echo "Successfully cleaned the directory."
else
    echo "You do not use a development repository."
fi

